-- MySQL Script generated by MySQL Workbench
-- 07/07/16 22:11:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ticket_event_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ticket_event_schema` ;

-- -----------------------------------------------------
-- Schema ticket_event_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticket_event_schema` DEFAULT CHARACTER SET utf8 ;
USE `ticket_event_schema` ;

-- -----------------------------------------------------
-- Table `ticket_event_schema`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`user_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`accounts` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`accounts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `role_id` INT(11) NOT NULL,
  `isActive` INT(11) NOT NULL,
  `active_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_id` (`role_id` ASC),
  CONSTRAINT `accounts_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `ticket_event_schema`.`user_roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`activity_layout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`activity_layout` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`activity_layout` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `event_id` INT(11) NOT NULL,
  `bg_image` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `event_logo` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `sologan` VARCHAR(300) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`act_lay_image_library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`act_lay_image_library` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`act_lay_image_library` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `act_id` INT(11) NOT NULL,
  `image` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `act_id` (`act_id` ASC),
  CONSTRAINT `act_lay_image_library_ibfk_1`
    FOREIGN KEY (`act_id`)
    REFERENCES `ticket_event_schema`.`activity_layout` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`event_layout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`event_layout` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`event_layout` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`event_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`event_type` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`event_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`events` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`events` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `type_id` INT(11) NOT NULL,
  `account_id` INT(11) NOT NULL,
  `layout_id` INT(11) NOT NULL,
  `create_date` DATE NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `address` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `organize_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `phone` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `organize_infor` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `isPublic` INT(1) NOT NULL,
  `isAccept` INT(1) NOT NULL DEFAULT '0',
  `image` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `layout_id` (`layout_id` ASC),
  INDEX `type_id` (`type_id` ASC),
  CONSTRAINT `events_ibfk_1`
    FOREIGN KEY (`layout_id`)
    REFERENCES `ticket_event_schema`.`event_layout` (`id`),
  CONSTRAINT `events_ibfk_2`
    FOREIGN KEY (`type_id`)
    REFERENCES `ticket_event_schema`.`event_type` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`comments` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `event_id` INT(11) NOT NULL,
  `account_id` INT(11) NULL DEFAULT NULL,
  `content` VARCHAR(300) CHARACTER SET 'utf8' NOT NULL,
  `comment_date` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `event_id` (`event_id` ASC),
  INDEX `comments_ibfk_2` (`account_id` ASC),
  CONSTRAINT `comments_ibfk_1`
    FOREIGN KEY (`event_id`)
    REFERENCES `ticket_event_schema`.`events` (`id`),
  CONSTRAINT `comments_ibfk_2`
    FOREIGN KEY (`account_id`)
    REFERENCES `ticket_event_schema`.`accounts` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`course_layout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`course_layout` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`course_layout` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `event_id` INT(11) NOT NULL,
  `banner_image` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `place_image` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `event_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`course_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`course_content` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`course_content` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `course_id` INT(11) NOT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `content` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `course_id` (`course_id` ASC),
  CONSTRAINT `course_content_ibfk_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `ticket_event_schema`.`course_layout` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`course_lay_speaker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`course_lay_speaker` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`course_lay_speaker` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_course_lay` INT(11) NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `filed` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `history` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `image` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_course_lay` (`id_course_lay` ASC),
  CONSTRAINT `course_lay_speaker_ibfk_1`
    FOREIGN KEY (`id_course_lay`)
    REFERENCES `ticket_event_schema`.`course_layout` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`free_layout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`free_layout` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`free_layout` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `event_id` INT(11) NOT NULL,
  `content` MEDIUMTEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`free_layout_image_library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`free_layout_image_library` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`free_layout_image_library` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_free_layout` INT(11) NOT NULL,
  `image` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_free_layout` (`id_free_layout` ASC),
  CONSTRAINT `free_layout_image_library_ibfk_1`
    FOREIGN KEY (`id_free_layout`)
    REFERENCES `ticket_event_schema`.`free_layout` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`music_layout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`music_layout` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`music_layout` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `event_id` INT(11) NOT NULL,
  `link_highlight` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `place_image` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`mus_lay_famous_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`mus_lay_famous_person` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`mus_lay_famous_person` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_music_layout` INT(11) NOT NULL,
  `image` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `dayofbirth` DATE NOT NULL,
  `tailent` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `history` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_music_layout` (`id_music_layout` ASC),
  CONSTRAINT `mus_lay_famous_person_ibfk_1`
    FOREIGN KEY (`id_music_layout`)
    REFERENCES `ticket_event_schema`.`music_layout` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`mus_lay_image_library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`mus_lay_image_library` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`mus_lay_image_library` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `mus_layout_id` INT(11) NOT NULL,
  `image` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `mus_layout_id` (`mus_layout_id` ASC),
  CONSTRAINT `mus_lay_image_library_ibfk_1`
    FOREIGN KEY (`mus_layout_id`)
    REFERENCES `ticket_event_schema`.`music_layout` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`tickets` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`tickets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `event_id` INT(11) NOT NULL,
  `prices` FLOAT NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `event_id` (`event_id` ASC),
  CONSTRAINT `tickets_ibfk_1`
    FOREIGN KEY (`event_id`)
    REFERENCES `ticket_event_schema`.`events` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`ticket_buyers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`ticket_buyers` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`ticket_buyers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ticket_id` INT(11) NOT NULL,
  `account_id` INT(11) NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `address` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `phone` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `gender` VARCHAR(4) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dayofbirth` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ticket_id` (`ticket_id` ASC),
  CONSTRAINT `ticket_buyers_ibfk_1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `ticket_event_schema`.`tickets` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ticket_event_schema`.`user_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_event_schema`.`user_information` ;

CREATE TABLE IF NOT EXISTS `ticket_event_schema`.`user_information` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `address` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `phone` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `gender` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `birthday` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `avatar` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_account_information`
    FOREIGN KEY (`id`)
    REFERENCES `ticket_event_schema`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
